name: refresh-versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - run: chmod +x gradlew
      - run: ./gradlew wrapper --gradle-version latest
      - run: ./gradlew refreshVersions
      - uses: peter-evans/create-pull-request@v6
